MVC/MVC_EXAM/MVC_EXAM/Models/pclass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_EXAM.Models
{
    public class pclass
    {
        public int catid { get; set; }
        public string catname { get; set; }
        
        public int pid { get; set; }
        public int cid { get; set; }

        public string pname { get; set; }
        public int  pcategory { get; set; }
        public int pprice { get; set; }
        public string pdetail { get; set; }
        public string pimage { get; set; }
    }
}

MVC/MVC_EXAM/MVC_EXAM/Controllers/adminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_EXAM.Models;

namespace MVC_EXAM.Controllers
{
    public class adminController : Controller
    {
        //
        // GET: /admin/

        db_rinkal_examEntities dc = new db_rinkal_examEntities();
        [HttpGet]
        public ActionResult addcat()
        {
            return View();
        }
        [HttpPost]
        public ActionResult addcat(pclass f)
        {
            tbl_category tr = new tbl_category();
            tr.catid = f.catid;
            tr.catname = f.catname;

            dc.tbl_category.Add(tr);
            dc.SaveChanges();
            ViewBag.msg = "Insert Succesfully..";
            return View();
        }
        [HttpGet]
        public ActionResult displaycat()
        {
            var p = from n in dc.tbl_category select n;
            var model = new List<pclass>();
            foreach (var item in p)
            {
                pclass f = new pclass();
                f.catid = item.catid;
                f.catname = item.catname;

                model.Add(f);
            }
            return View(model);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var p = (from n in dc.tbl_category where n.catid == id select n).FirstOrDefault();
           
            pclass f = new pclass();
            f.catid = p.catid;
            f.catname = p.catname;

            return View(f);
        }
        [HttpPost]
        public ActionResult Edit(int id,pclass f)
        {
            var p = (from n in dc.tbl_category where n.catid == id select n).FirstOrDefault();

            //p.catid = f.catid;
            p.catname=f.catname;

            dc.SaveChanges();
            return RedirectToAction("displaycat");
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var p = (from n in dc.tbl_category where n.catid == id select n).FirstOrDefault();

            pclass f = new pclass();
            f.catid = p.catid;
            f.catname = p.catname;

            return View(f);
        }
        [HttpPost]
        public ActionResult Delete(int id, pclass f)
        {
            var p = (from n in dc.tbl_category where n.catid == id select n).FirstOrDefault();

           // p.catid = f.catid;
           //p.catname = f.catname;

            dc.tbl_category.Remove(p);
            dc.SaveChanges();
            return RedirectToAction("displaycat");
        }
       
    }
}

MVC/MVC_EXAM/MVC_EXAM/Controllers/userController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_EXAM.Models;

namespace MVC_EXAM.Controllers
{
    public class userController : Controller
    {
        //
        // GET: /user/
        db_rinkal_examEntities dc = new db_rinkal_examEntities();
        string filename, path, fulpath, temp;
        [HttpGet]
        public ActionResult addproduct()
        {
            ViewBag.cat = new SelectList(dc.tbl_category, "catid", "catname");
            return View();
        }
        [HttpPost]
        public ActionResult addproduct(pclass f, HttpPostedFileBase file1)
        {
            ViewBag.cat = new SelectList(dc.tbl_category, "catid", "catname");
            tbl_product pr = new tbl_product();
            pr.pname = f.pname;
            pr.pcategory = f.catid;
            pr.pprice = f.pprice;
            pr.pdetail = f.pdetail;
            if (file1 != null)
            {
                filename = file1.FileName;
                path = Server.MapPath("~/img/");
                fulpath = path + filename;
                file1.SaveAs(fulpath);
                temp = "~/img/" + filename;
            }
            else
            {
                temp = "";
            }
            pr.pimage = temp;
            dc.tbl_product.Add(pr);
            dc.SaveChanges();
            return View();
        }
        [HttpGet]
        public ActionResult viewproduct()
        {
            ViewBag.cat = new SelectList(dc.tbl_category, "catid", "catname");

            var p = from n in dc.tbl_product join m in dc.tbl_category on n.pcategory equals m.catid select new {n.pname,n.pdetail,n.pprice,n.pimage ,m.catname};
            var model = new List<pclass>();
            foreach (var item in p)
            {
                pclass f = new pclass();
                f.pname = item.pname;
                f.catname = item.catname;
                f.pprice = int.Parse(item.pprice.ToString());
                f.pdetail = item.pdetail;
                f.pimage = item.pimage;

                model.Add(f);
            }
            return View(model);


        }
    }
}

MVC/MVC_EXAM/MVC_EXAM/Views/user/addproduct.cshtml
@model MVC_EXAM.Models.pclass

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>addproduct</title>
</head>
<body>
    <div>
        @using (Html.BeginForm("addproduct", "user", FormMethod.Post, new {enctype="multipart/form-data" }))
        {
            <table align="center" border="1">
                <tr>
                    <td>
                        Product Name:
                    </td>
                    <td>
                        @Html.TextBoxFor(v=>v.pname)
                     </td>
                </tr>
                <tr>
                    <td>
                        Product Category:
                    </td>
                    <td>
                        @Html.DropDownListFor(v=>v.catid,new SelectList(ViewBag.cat,"value","text"),"select category")
                    </td>
                </tr>
                <tr>
                    <td>
                        Pprice:
                    </td>
                    <td>@Html.TextBoxFor(v=>v.pprice)</td>
                </tr>
                <tr>
                    <td>
                        Pdetail:
                    </td>
                    <td>
                        @Html.TextBoxFor(v=>v.pdetail)
                    </td>
                </tr>
                <tr>
                    <td>
                        PImage:
                    </td>
                    <td>
                        <input type="file" name="file1" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <input type="submit" value="Submit" />
                    </td>
                </tr>
            </table>
        }
    </div>
</body>
</html>

MVC/MVC_EXAM/MVC_EXAM/Views/user/viewproduct.cshtml
@model IEnumerable< MVC_EXAM.Models.pclass>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>viewproduct</title>
</head>
<body>
    <div>

        <table>
            @foreach (var item in Model)
            {
             <tr>
                <td>
                    Product Name:
                </td>
                <td>
                    @Html.DisplayFor(v=>item.pname)
                </td>     
                <td>
                    Product Category
                </td>
              @*  <td>
                    @Html.DropDownListFor(v => item.pcategory, new SelectList(ViewBag.cat, "value", "text"), "Select Category", new {onchange = "document.location.href = '/user/viewproduct?id=' + this.options[this.selectedIndex].value;" })
                </td>*@
                 <td>
                    @Html.DisplayFor(v=>item.catname)

                 </td>
                <td>
                    Product Price
                </td>
                <td>
                    @Html.DisplayFor(v=>item.pprice)
                </td>
                <td>
                    Product Detail:
                </td>
                <td>
                    @Html.DisplayFor(v=>item.pdetail)
                </td>
                <td>
                    Product Image
                </td>
                <td>
                    <img src="@Url.Content(item.pimage)" height="50px" width="50px" />
                </td>
            </tr>  
            }
            
        </table>
    </div>
</body>
</html>